// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED BY `tool/generate_hashes.dart`. TO UPDATE, RUN
//
//    dart run tool/generate_hashes.dart
//

import 'package:native_assets_cli/native_assets_cli.dart';

const fileHashes = <(OS, Architecture), String>{
    (OS.linux, Architecture.x64):
      '375d29ba3bb86eab2665c0d1dcac1d35e3b5d0ea6bff5d40cfac322a66239a28',
    (OS.macOS, Architecture.arm64):
      '375d29ba3bb86eab2665c0d1dcac1d35e3b5d0ea6bff5d40cfac322a66239a28',
    (OS.windows, Architecture.x64):
      '375d29ba3bb86eab2665c0d1dcac1d35e3b5d0ea6bff5d40cfac322a66239a28'
};
